import React from 'react';
import Popover from '@material-ui/core/Popover';
import Typography from '@material-ui/core/Typography';
import Box from '@material-ui/core/Box';
import HelpIcon from '@material-ui/icons/Help';
import IconButton from '@material-ui/core/IconButton';
import {theme} from './theme';
import useStyles from "./styles";



export default function PTSHelp() {
  const [anchorEl, setAnchorEl] = React.useState(null);
  const classes = useStyles();                        


  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  const open = Boolean(anchorEl);
  const id = open ? 'simple-popover' : undefined;

  return (
    <>
        {/* <IconButton aria-describedby={id} style={{color:"white"}}  onClick={handleClick}> */}
        <IconButton aria-describedby={id} className={classes.helpIcon}  onClick={handleClick}>
            <HelpIcon/>
        </IconButton>
        
        <Popover
            id={id}
            open={open}
            anchorEl={anchorEl}
            onClose={handleClose}
            anchorOrigin={{
                vertical: 'bottom',
                horizontal: 'center',
            }}
            transformOrigin={{
                vertical: 'top',
                horizontal: 'center',
            }}
            
        >

             <Typography variant="h6" > 
                <Box fontWeight='fontWeightBold' display='inline'>Background</Box> 
            </Typography>

            <Typography component="div" >Check Test Results is generated by running the 
                <Box fontWeight='fontWeightBold' display='inline'> check-tests
                </Box> command in the Phoronix Test Suite.
            </Typography> 
            <br/>
            
            <Typography variant="h6"> 
                <Box fontWeight='fontWeightBold' display='inline'>Navigating The Page</Box> 
            </Typography>

            <Typography component="div">Click on a 
                <Box fontWeight='fontWeightBold' style={{color:theme.palette.primary.main}} display='inline'> Profile, </Box>
                to see Packages belonging to the test profile. 
                Click on the 
                <Box fontWeight='fontWeightBold' style={{color:theme.palette.primary.main}} display='inline'> Package, </Box>
                 to see package details. 
                Click on the 
                <Box fontWeight='fontWeightBold' style={{color:theme.palette.primary.main}} display='inline'> Mirror, </Box>
                to see Mirror details, including Failures.
                Hint: Any colored text can be clicked.
            </Typography>
            <br/>

            <Typography component="div">Successful tests appear in  
                <Box fontWeight='fontWeightBold' style={{color:theme.palette.primary.main}} display='inline'> blue. </Box>
                Failed tests appear in  
                <Box fontWeight='fontWeightBold' style={{color:theme.palette.secondary.main}} display='inline'> red. </Box> 
            </Typography>
            <br/>

            <Typography component="div" variant="h6"> 
                <Box fontWeight='fontWeightBold' display='inline'>Filters</Box> 
            </Typography>
            <Typography component="div">Tests can be filtered based on what you want to see.</Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> All Tests:</Box> Displays all the tests. Default.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> All Fails:</Box> Displays all tests that failed.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> MD5 Fails:</Box> Displays all tests which failed the MD5 checksum.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> SHA256 Fails:</Box> Displays all tests which failed the SHA256 checksum.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> Rediects:</Box> Displays all tests which resulted in a HTTP 301 or 302 status.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> Not Tested:</Box> Displays all tests which were not tested and have no results.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> Timed Out:</Box> Displays all tests which failed to download due to a time out.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> Profile Name:</Box> Searches for the test with the given profile name. Can be used in conjunction with the filters.
            </Typography>
               
            <br/>

            <Typography variant="h6"> 
                <Box fontWeight='fontWeightBold' display='inline'>Explaination of Terms</Box> 
            </Typography>
            <Typography component="div" >Each Test Profile contains one or more 
                <Box fontWeight='fontWeightBold' display='inline'> packages. </Box>
                Each Package contains one or more 
                <Box fontWeight='fontWeightBold' display='inline'> mirrors. </Box> 
            </Typography>
            <br/>
            

            <Typography component="div"> 
                <Box fontWeight='fontWeightBold' display='inline'> Packages</Box> contain:
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> File Name:</Box> Name of the file downloaded from the vendor.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> File Size: </Box> Size of the file downloaded from the vendor.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> SHA256: </Box> SHA256 Key if provided. May be blank. 
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'> MD5: </Box> MD5 Key if provided. May be blank. 
            </Typography>
            <br/>

            <Typography component="div"> 
                <Box fontWeight='fontWeightBold' display='inline'> Mirrors</Box> contain:
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>Status:</Box> The test passed or failed.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>Source: </Box> The test was identical to a previously downloaded test and was reused.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>URL: </Box> The location of the downloaded test. In most cases this will download the test. 
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>Download Time: </Box> The time taken in millisecs to download the test. 
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>Redirect To: </Box> URL used when HTTP 302 Redirect is encountered. 
            </Typography>
        
            <br/>
            <Typography component="div"> 
                <Box fontWeight='fontWeightBold' display='inline'> Failures</Box> contain:
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>File Size:</Box> The file size downloaded does not match the package filesize.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>MD5: </Box> The MD5 checksum does not match the package MD5 checksum.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>SHA256: </Box> The SHA256 checksum does not match the package MD5 checksum. 
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>Vendor: </Box> Returned HTTP Status Code when attempting to download file.
            </Typography>
            <Typography component="div">
                <Box ml={5} fontWeight='fontWeightBold' display='inline'>Timed Out: </Box> File failed to download due to a curl time out.
            </Typography> 
        </Popover> 
    </>
  );
}